carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cartView, name='cart-view'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_cart/<int:product_id>/', views.remove_cart, name='remove_cart'),
]

e_commerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.home, name='home'),
    path('store/', views.storeView, name='store'),
    path('store/category/<slug:category_slug>/', views.storeItemView, name='product_by_category'),
    path('store/<slug:category_slug>/<slug:product_slug>/', views.storeDetailView, name='product_detail'),
    path('search/', views.search_items, name='search')
]

products/models.py
from django.db import models
from django.urls import reverse
from category.models import Category


class Product(models.Model):
    title = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(max_length=150, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.IntegerField()
    stock = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/products/')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_product_url(self):
        return reverse('products:product_detail', kwargs={'category_slug': self.category.slug, 'product_slug': self.slug})


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color')

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size')


VARIATION_CATEGORY_CHOICE = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=VARIATION_CATEGORY_CHOICE)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

products/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Product
from category.models import Category
from carts.models import CartItem
from carts.views import _cart_id


def home(request):
    products = Product.objects.all().filter(is_available=True)
    product_count =  products.count()
    context = {
        'products': products,
        'product_count': product_count
    }
    return render(request, 'products/home.html', context)

def storeView(request):
    products = Product.objects.all().filter(is_available=True).order_by('id')
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    paged_product = paginator.get_page(page)
    product_count = products.count()
    context = {
        'products': paged_product,
        'product_count': product_count
    }
    return render(request, 'products/store.html', context)

def storeItemView(request, category_slug):
    categories = None
    products = None
    if category_slug != None:
        products = Product.objects.all().filter(category__slug=category_slug, is_available=True)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True)
        product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count
    }
    return render(request, 'products/store.html', context)


def storeDetailView(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=product)
    except Exception as e:
        raise e
    context = {
        'product': product,
        'in_cart': in_cart,
    }
    return render(request, 'products/product_detail.html', context)

def search_items(request):
    product = None
    product_count = 0
    if 'keyword' in request.path:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(discription__icontains=keyword) | Q(title__icontains=keyword))
            product_count = product.count()
    return render(request, 'products/store.html', {'products': products, 'product_count': product_count,})

templates/products/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% include "include/navbar.html" %}
<!-- ========================= SECTION MAIN ========================= -->
{% include "messages.html" %}
<section class="section-intro padding-y-sm">
    <div class="container">

        <div class="intro-banner-wrap">
            <img src="{% static 'images/banners/1.jpg' %}" class="img-fluid rounded">
        </div>

    </div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->

<section class="section-name padding-y-sm">
    <div class="container">

        <header class="section-heading">
            <a href=".{% url 'products:store' %}" class="btn btn-outline-primary float-right">See all</a>
            <h3 class="section-title">Popular products</h3>
        </header><!-- sect-heading -->


        <div class="row">
            {% for single_product in products %}
            <div class="col-md-3">
                <div class="card card-product-grid">
                    <a href="{{ single_product.get_product_url }}" class="img-wrap"> <img src="{{ single_product.image.url }}"> </a>
                    <figcaption class="info-wrap">
                        <a href="{{ single_product.get_product_url }}" class="title">{{ single_product.title }}</a>
                        <div class="price mt-1">INR {{ single_product.price }}</div> <!-- price-wrap.// -->
                    </figcaption>
                </div>
            </div> <!-- col.// -->
            {% endfor %}
        </div> <!-- row.// -->

    </div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->

{% include "include/footer.html" %}

{% endblock content %}

templates/products/product_detail.html
{% extends 'base.html' %}


{% block content %}
{% include "include/navbar.html" %}
<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <a href="#"><img src="{{ product.image.url }}"></a>
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'carts:add_to_cart' product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">

              <h2 class="title">{{ product.title }}s</h2>

              <div class="mb-3">
                <var class="price h4">INR {{ product.price }}</var>
              </div>

              <p>{{ product.description }}</p>


              <hr>
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>Choose Color</option>
                    {% for i in product.variation_set.colors %}
                    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>Choose Color</option>
                    {% for i in product.variation_set.sizes %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              <hr>
              {% if product.stock <= 0 %} <h5 class="text-danger">Out of Stock</h5>
                {% else %}
                {% if in_cart %}
                <a href="{% url 'carts:add_to_cart' product.id %}" class="btn btn-success"> <span class="text">Add to
                    cart</span> <i class="fas fa-check"></i> </a>
                <a href="{% url 'carts:cart-view' %}" class="btn  btn-outline-primary"> <span class="text">View
                    Cart</span> <i class="fas fa-eye"></i> </a>
                {% else %}
                <button type="submit" class="btn btn-primary"><span class="text">Add to
                    cart</span><i class="fas fa-shopping-cart"></i> </button>
                {% endif %}
                {% endif %}
            </article> <!-- product-info-aside .// -->
          </form>
        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">

        <header class="section-heading">
          <h3>Customer Reviews</h3>

        </header>

        <article class="box mb-3">
          <div class="icontext w-100">
            <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
            <div class="text">
              <span class="date text-muted float-md-right">24.04.2020</span>
              <h6 class="mb-1">Mike John </h6>

            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <p>
              Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
              quis nostrud exercitation ullamco laboris nisi ut aliquip
            </p>
          </div>
        </article>



      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% include "include/footer.html" %}
{% endblock content %}

templates/products/store.html
{% extends 'base.html' %}

{% block content %}

        
        
        {% include "include/navbar.html" %}
        
        
        
        <!-- ========================= SECTION CONTENT ========================= -->
        <section class="section-content padding-y">
        <div class="container">
        
        <div class="row">
            <aside class="col-md-3">
                
        <div class="card">
            <article class="filter-group">
                <header class="card-header">
                    <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                        <i class="icon-control fa fa-chevron-down"></i>
                        <h6 class="title">Categories</h6>
                    </a>
                </header>
                <div class="filter-content collapse show" id="collapse_1" style="">
                    <div class="card-body">
                        
                        <ul class="list-menu">
                            <li><a href="{% url 'products:store' %}">All Products</a></li>
                            {% for category in links %}
                                <li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
                            {% endfor %}
                        </ul>
        
                    </div> <!-- card-body.// -->
                </div>
            </article> <!-- filter-group  .// -->
            <article class="filter-group">
                <header class="card-header">
                    <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                        <i class="icon-control fa fa-chevron-down"></i>
                        <h6 class="title">Sizes </h6>
                    </a>
                </header>
                <div class="filter-content collapse show" id="collapse_4" style="">
                    <div class="card-body">
                      <label class="checkbox-btn">
                        <input type="checkbox">
                        <span class="btn btn-light"> XS </span>
                      </label>
        
                      <label class="checkbox-btn">
                        <input type="checkbox">
                        <span class="btn btn-light"> SM </span>
                      </label>
        
                      <label class="checkbox-btn">
                        <input type="checkbox">
                        <span class="btn btn-light"> LG </span>
                      </label>
        
                      <label class="checkbox-btn">
                        <input type="checkbox">
                        <span class="btn btn-light"> XXL </span>
                      </label>
                </div><!-- card-body.// -->
                </div>
            </article> <!-- filter-group .// -->
            
            <article class="filter-group">
                <header class="card-header">
                    <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                        <i class="icon-control fa fa-chevron-down"></i>
                        <h6 class="title">Price range </h6>
                    </a>
                </header>
                <div class="filter-content collapse show" id="collapse_3" style="">
                    <div class="card-body">
                        
                        <div class="form-row">
                        <div class="form-group col-md-6">
                          <label>Min</label>
                          <!-- <input class="form-control" placeholder="$0" type="number"> -->
                              <select class="mr-2 form-control">
                                <option value="0">$0</option>
                                <option value="50">$50</option>
                                <option value="100">$100</option>
                                <option value="150">$150</option>
                                <option value="200">$200</option>
                                <option value="500">$500</option>
                                <option value="1000">$1000</option>
                            </select>
                        </div>
                        <div class="form-group text-right col-md-6">
                          <label>Max</label>
                              <select class="mr-2 form-control">
                                <option value="50">$50</option>
                                <option value="100">$100</option>
                                <option value="150">$150</option>
                                <option value="200">$200</option>
                                <option value="500">$500</option>
                                <option value="1000">$1000</option>
                                <option value="2000">$2000+</option>
                            </select>
                        </div>
                        </div> <!-- form-row.// -->
                        <button class="btn btn-block btn-primary">Apply</button>
                    </div><!-- card-body.// -->
                </div>
            </article> <!-- filter-group .// -->
            
        </div> <!-- card.// -->
        
            </aside> <!-- col.// -->
            <main class="col-md-9">
        
        <header class="border-bottom mb-4 pb-3">
                <div class="form-inline">
                    <span class="mr-md-auto">Found {{ product_count }} Items </span>
                    
                </div>
        </header><!-- sect-heading -->
        
        <div class="row">
            {% for single_product in products %}
            <div class="col-md-4">
                <figure class="card card-product-grid">
                    <div class="img-wrap"> 
                        
                        <a href="{{ single_product.get_product_url }}"><img src="{{ single_product.image.url }}"></a>
                        
                    </div> <!-- img-wrap.// -->
                    <figcaption class="info-wrap">
                        <div class="fix-height">
                            <a href="{{ single_product.get_product_url }}" class="title">{{ single_product.title }}e</a>
                            <div class="price-wrap mt-2">
                                <span class="price">INR {{ single_product.price }}</span>
                            </div> <!-- price-wrap.// -->
                        </div>
                        <a href="{{ single_product.get_product_url }}" class="btn btn-block btn-primary">View Details</a>
                    </figcaption>
                </figure>
            </div> <!-- col.// -->
            {% endfor %}
        </div> <!-- row end.// -->
        
        
        <nav class="mt-4" aria-label="Page navigation sample">
        {% if products.has_other_pages %}
          <ul class="pagination">
                {% if products.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                {% endif %}
            {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if products.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
        {% endif %}
        </nav>
        
            </main> <!-- col.// -->
        
        </div>
        
        </div> <!-- container .//  -->
        </section>
        <!-- ========================= SECTION CONTENT END// ========================= -->
        
{% include "include/footer.html" %}
{% endblock content %}