carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cartView, name='cart-view'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_cart/<int:product_id>/', views.remove_cart, name='remove_cart'),
]

e_commerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.home, name='home'),
    path('store/', views.storeView, name='store'),
    path('store/category/<slug:category_slug>/', views.storeItemView, name='product_by_category'),
    path('store/<slug:category_slug>/<slug:product_slug>/', views.storeDetailView, name='product_detail'),
    path('search/', views.search_items, name='search')
]

carts/models.py
from django.db import models
from products.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=255, blank=True)
    added_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.title

    def sub_total(self):
        return (self.product.price * self.quantity)

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from products.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist



def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variation = []
    if request.method == "POST":
        for item in request.POST:
            key = item
            value = request.POST[key]
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except:
                pass      
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        # if len(product_variation) > 0:
        #     for item in product_variation:
        #         cart_item.variations.add(item)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        CartItem.objects.create(
            product = product,
            cart = cart,
            quantity = 1
        )
        # if len(product_variation) > 0:
        #     for item in product_variation:
        #         cart_item.variations.add(item)
        cart.save()
    return redirect('carts:cart-view')

def remove_from_cart(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('carts:cart-view')


def remove_cart(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = Product.objects.get(id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    cart_item.delete()
    return redirect('carts:cart-view')


def cartView(request, total=0, quantity=0, cart_items=None):
    tax=0 
    grand_total=0
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
            if total >= 1:
                tax = (2.5 * total) / 100
                grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'carts/cart.html', context)

templates/carts/cart.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% include "include/navbar.html" %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
        <h2 class="text-center mb-4">Your Shopping cart is Empty</h2>
        <div class="text-center mt-4">
            <a href="{% url 'products:store' %}" class="btn btn-primary text-center">Continue Shopping</a>
        </div>
        {% else %}
        
        <div class="row">
            <aside class="col-lg-9">
        <div class="card">
        <table class="table table-borderless table-shopping-cart">
        <thead class="text-muted">
        <tr class="small text-uppercase">
        <th scope="col">Product</th>
        <th scope="col" width="120">Quantity</th>
        <th scope="col" width="120">Price</th>
        <th scope="col" class="text-right" width="200"> </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
            <td>
                <figure class="itemside align-items-center">
                    <div class="aside"><a href="{{ cart_item.product.get_product_url }}"><img src="{{ cart_item.product.image.url }}" class="img-sm"></a></div>
                    <figcaption class="info">
                        <a href="{{ cart_item.product.get_product_url }}" class="title text-dark">{{ cart_item.product.title }}</a>
                        <p class="text-muted small">Color: 25 Mpx <br> Brand: Canon</p>
                    </figcaption>
                </figure>
            </td>
            <td> 
                <!-- col.// -->
                            <div class="col"> 
                                <div class="input-group input-spinner">
                                    <div class="input-group-prepend">
                                    <a href="{% url 'carts:remove_from_cart' cart_item.product.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                    </div>
                                    <input type="text" class="form-control"  value="{{ cart_item.quantity }}">
                                    <div class="input-group-append">
                                    <a href="{% url 'carts:add_to_cart' cart_item.product.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
                                    </div>
                                </div> <!-- input-group.// -->
                            </div> <!-- col.// -->
            </td>
            <td> 
                <div class="price-wrap"> 
                    <var class="price">${{ cart_item.sub_total }}</var> 
                    <small class="text-muted"> ${{ cart_item.product.price }} each </small> 
                </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right"> 
            <a href="{% url 'carts:remove_cart' cart_item.product.id %}" class="btn btn-danger"> Remove</a>
        </td>
        {% endfor %}
        </tbody>
        </table>
        </div> <!-- card.// -->
        
            </aside> <!-- col.// -->
            <aside class="col-lg-3">
        
                <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                    <dt>Total price:</dt>
                    <dd class="text-right">${{ total }}7</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Tax:</dt>
                    <dd class="text-right"> ${{ tax }}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Grand Total:</dt>
                    <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
                    </dl>
                    <hr>
                    <p class="text-center mb-3">
                        <img src="{% static './images/misc/payments.png' %}" height="26">
                    </p>
                    <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                    <a href="{% url 'products:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                </div> <!-- card-body.// -->
                </div> <!-- card.// -->
        
        </aside> <!-- col.// -->
        
        
        </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    {% include "include/footer.html" %}
{% endblock content %}